### ISSUE TITLE
How can I add some text along with loader?

### ISSUE THREAD

**Issue by pvdutils** [amarinediary/Vanilla-JS-Pages-Transitions-Loader#2]
Your page loader is too good and simple. How can I add some text along with loader animation. Basically I want to add my page title be displayed just above the loader animation.
Pl.help

**Comment by amarinediary** [comment]
Hi @pvdutils, First of all thank you for the kind words.

The easiest approach would be to create a new element, append it to the self `<div>` (`var a`) generated element and place it around through css by adding it to the already self generated css tag.

But I would advise against that. The loader approach is just a bandaid in regards to poor performances handling (eg: font loading/swap, initial html blink... ).
You don't want it to show up for too long and you usually don't have the time to read... having too much stuff on a loading screen could confuse users into thinking an action on their end is needed...

**Comment by pvdutils** [comment]
Great. Thanks for quick reply !
